name: Sync to UVA 2025

on:
  push:
    branches:
      - main  # O la rama que uses (master/main)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout privado
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
  
      - name: Limpieza de rastro
        run: |
          # 1. Borramos la carpeta .git para que sea un repo nuevo
          rm -rf .git
          
          # 2. Limpieza de comentarios (usando una forma que no de error si no hay coincidencias)
          sed -i 's///g' slides.md || true
          sed -i 's///g' slides.md || true

          # 3. Configuramos Git pero NO inicializamos (la acción cpina se encarga de la lógica de Git)
          git config --global user.name "mhercol"
          git config --global user.email "mhercol@gmail.com"

      - name: Push al repo público
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.UVA_DEPLOY_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'mhercol'
          destination-repository-name: 'Forense-de-red-UVA-2026'
          user-email: 'mhercol@gmail.com'
          target-branch: main
